CREATE TABLE CLIENTE (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	NOME VARCHAR(64) NOT NULL,
	CPF VARCHAR(20) NOT NULL,	
	CARTAO VARCHAR(64) NOT NULL,
	SALDOINICIAL DECIMAL(12,2) NOT NULL,
	SENHA VARCHAR(6) NOT NULL,
	CONSTRAINT PK_PERMISSOES PRIMARY KEY (ID),
	CONSTRAINT UN_CARTAO UNIQUE (CARTAO),
	CONSTRAINT UN_CPF UNIQUE (CPF)
);

CREATE TABLE MOVIMENTO_SALDO_CLIENTE (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	CLIENTE BIGINT NOT NULL,
	NATUREZA CHAR DEFAULT 'C' NOT NULL CHECK (NATUREZA = 'C' OR NATUREZA = 'D'),
	VALOR DECIMAL(12, 2) NOT NULL,
	DTMOVIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT PK_MOVIMENTO PRIMARY KEY (ID),
	CONSTRAINT REF_CLIENTE FOREIGN KEY (CLIENTE) 
	REFERENCES CLIENTE(ID) ON DELETE RESTRICT ON UPDATE NO ACTION
);

CREATE TRIGGER TRIG_SALDO_INICIAL AFTER INSERT ON CLIENTE REFERENCING NEW AS N FOR EACH ROW BEGIN
	INSERT INTO MOVIMENTO_SALDO_CLIENTE (ID, CLIENTE, NATUREZA, VALOR, DTMOVIMENTO) VALUES (DEFAULT, N.ID, 'C', N.SALDOINICIAL, DEFAULT);
END;